#!/usr/bin/env bash
# install.sh — set up Ardi auto-mining as a systemd user service.
#
# This is INTENDED TO BE INVOKED BY AN LLM AGENT, not typed by a human.
# It is fully non-interactive:
#   - Auto-detects which runtime CLI is installed (claude / hermes / openclaw)
#   - Picks sensible defaults for everything
#   - Does NOT prompt for or require any LLM API key — the runtime CLI
#     uses its own credentials (~/.claude/, ~/.hermes/, etc.)
#   - Idempotent: safe to re-run
#   - Auto-starts the timer on success
#
# Exit codes:
#   0  — installed (or already installed) and timer is running
#   64 — no runtime CLI found on PATH (need claude or hermes or openclaw)
#   65 — ardi-agent missing
#   66 — systemd not available (e.g. running in a container without it)

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
INSTALL_DIR="$HOME/.local/share/ardi-auto-mine"
ENV_FILE="$HOME/.ardi-agent/auto-mine.env"
SYSTEMD_USER_DIR="$HOME/.config/systemd/user"

say() { printf "▸ %s\n" "$*"; }
warn() { printf "⚠ %s\n" "$*" >&2; }

# ── Preflight ───────────────────────────────────────────────────────
command -v ardi-agent >/dev/null || {
  warn "ardi-agent not on PATH — install the skill first"
  exit 65
}
command -v systemctl >/dev/null || {
  warn "systemctl not available — auto-mine requires systemd"
  exit 66
}

# Auto-detect runtime CLI
RUNTIME=""
for cand in claude hermes openclaw; do
  if command -v "$cand" >/dev/null; then
    RUNTIME="${cand}"
    break
  fi
done
[[ -z "$RUNTIME" ]] && {
  warn "no LLM runtime CLI found. Install one of: claude, hermes, openclaw."
  warn "Then re-run this script."
  exit 64
}
# Map openclaw → openclaw-scripted (the systemd-timer-driven mode)
[[ "$RUNTIME" == "openclaw" ]] && RUNTIME="openclaw-scripted"
say "auto-detected runtime: $RUNTIME"

# ── 1. Stable symlink to this directory ─────────────────────────────
say "linking $HERE → $INSTALL_DIR"
mkdir -p "$(dirname "$INSTALL_DIR")"
ln -snf "$HERE" "$INSTALL_DIR"

# ── 2. Env file with sensible defaults — NO API key required ────────
say "writing env at $ENV_FILE"
mkdir -p "$(dirname "$ENV_FILE")"
if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" <<EOF
# ardi auto-mine env — generated by install.sh.
# Edit only if you need to override defaults.
#
# No API key here on purpose: your runtime CLI ($RUNTIME) uses its
# own credentials. If you can run \`$RUNTIME\` interactively, the
# systemd-spawned subagent inherits the same auth.

ARDI_AGENT_RUNTIME=$RUNTIME
ARDI_AGENT_BIN=$(command -v ardi-agent)
MAX_PER_EPOCH=3
EOF
  chmod 600 "$ENV_FILE"
else
  say "env already exists; not overwriting"
fi

# ── 3. systemd user units ───────────────────────────────────────────
say "installing systemd user units"
mkdir -p "$SYSTEMD_USER_DIR"
sed "s|%h/ardi-skill/tools/auto-mine|$INSTALL_DIR|g" \
  "$HERE/systemd/ardi-mine.service" > "$SYSTEMD_USER_DIR/ardi-mine.service"
cp "$HERE/systemd/ardi-mine.timer" "$SYSTEMD_USER_DIR/ardi-mine.timer"
systemctl --user daemon-reload
systemctl --user enable ardi-mine.timer 2>&1 | tail -1

# ── 4. Auto-start ───────────────────────────────────────────────────
say "starting timer"
systemctl --user start ardi-mine.timer

# ── 5. Verify ───────────────────────────────────────────────────────
sleep 1
if systemctl --user is-active ardi-mine.timer >/dev/null; then
  say "✓ auto-mine running. Next tick within 90s."
  say "  watch: journalctl --user -u ardi-mine -f"
  say "  status: ardi-agent auto-mine status   (or run $INSTALL_DIR/status.sh)"
  exit 0
else
  warn "timer failed to start; see: systemctl --user status ardi-mine.timer"
  exit 1
fi
